In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/shsarv/Machine-Learning-Projects/main/Diabetes%20Prediction%20%5BEND%202%20END%5D/dataset/kaggle_diabetes.csv")

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
X = df.drop('Outcome',axis = 1)
y = df['Outcome']

In [8]:
#splitting data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [10]:
lg = LogisticRegression()

In [11]:
lg.fit(X_train,y_train)

c:\Users\singh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
X_test.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
532            1       86             66             52       65  41.3   

     DiabetesPedigreeFunction  Age  
532                     0.917   29

In [14]:
lg.predict(X_test.head(1))

array([0], dtype=int64)

In [16]:
np.array(X_test.head(1))

array([[ 1.   , 86.   , 66.   , 52.   , 65.   , 41.3  ,  0.917, 29.   ]])

In [17]:
X_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
532             1       86             66             52       65  41.3   
656             2      101             58             35       90  21.8   
1612            1      196             76             36      249  36.5   
1589            6      139             84             37        0  50.7   
62              5       44             62              0        0  25.0   

      DiabetesPedigreeFunction  Age  
532                      0.917   29  
656                      0.155   22  
1612                     0.875   29  
1589                     0.320   50  
62                       0.587   36

In [18]:
lg.predict([[1.0,90.3,70,55,89,45.3,0.25,50]])

c:\Users\singh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [28]:
X_train.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [27]:
import pickle
with open('model.pickle','wb') as model:
    pickle.dump(lg,model)

In [26]:
with open('model.pickle','rb') as new:
    mg = pickle.load(new)

EOFError: Ran out of input